### ISSUE TITLE
 Request: idea that can spark some more PVP.

### ISSUE THREAD

**Issue by dorimanx** [LordTylus/SE-Torch-Plugin-ALE-Biggest-Grids-Broadcast#6]
We have one more idea that can spark some PVP.

Idea is this:
When there is no BIG player with maxed PCU online, and no one to hunt!
then show next 3 TOP PCU users! lets say only ships...
So there is always some one to hunt! :)

idea is if we set to show above 80K PCU but no one online, then show TOP players that have from 60K to max set (80K)

**Comment by LordTylus** [comment]
This sounds like its already in place.

When you say Top 3 players it takes the Top 3 players which are online.

If the Player with the most PCU is not there, Top 1 will be the one with second most PCU.

So essentially what you describe is already there. Nothing to do here.

**Comment by dorimanx** [comment]
well, not really what i had in mind:
Lets say that i have set max PCU to 80K.
All players that have above 80K are offline now.
But we have other people with 70K+ ships online! they are not spotted.

So idea was, if no above max pcu players online then show the most FAT 3 players that are ONLINE.
but still have limit MIN PCU range... (configurable value) in my case 70K.

**Comment by LordTylus** [comment]
As I said I dont see the difference between that actually. I mean just set the limit to 70k and your players will be broadcasted anyway if no 80+ guy is on.

I see where you are getting at tho. basically you ant the top 5 with 80 and the top 3 with 70 only if noone of the top 5 is there or something like that.

However I dont plan on implementing something like that anytime soon. Because its pretty confusing to configure and for players to understand.
